# Generated by Django 2.2.5 on 2019-09-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField()),
                ('claim_type', models.CharField(max_length=100)),
                ('contract', models.BigIntegerField(null=True)),
                ('po', models.BigIntegerField(null=True)),
                ('original_value', models.BigIntegerField()),
                ('estimated_value', models.BigIntegerField()),
                ('nature', models.CharField(max_length=100)),
                ('initiated_by', models.CharField(max_length=20)),
                ('responsible_rep', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=20)),
                ('status', models.CharField(default='open', max_length=20)),
                ('bus_unit', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resolution', models.CharField(max_length=100)),
                ('close_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.BigIntegerField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('claim_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Claim')),
            ],
        ),
    ]
