# Generated by Django 2.1.15 on 2019-12-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField(null=True)),
                ('claim_type', models.CharField(max_length=100, null=True)),
                ('contract', models.BigIntegerField(blank=True, default=None, null=True)),
                ('po', models.BigIntegerField(blank=True, default=None, null=True)),
                ('original_value', models.BigIntegerField(null=True)),
                ('estimated_value', models.BigIntegerField(null=True)),
                ('nature', models.CharField(max_length=100, null=True)),
                ('initiated_by', models.CharField(max_length=20, null=True)),
                ('responsible_rep', models.CharField(max_length=100, null=True)),
                ('projects', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('bus_unit', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('resolution', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('close_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.BigIntegerField(default=None, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_claim_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Claim')),
            ],
        ),
    ]
