# Generated by Django 2.2.5 on 2019-09-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='claim_ref',
            new_name='vendor_claim_ref',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('comment_claim_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Claim')),
            ],
        ),
    ]
