# Generated by Django 2.2.5 on 2019-10-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190925_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_claim_ref',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_type',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
