# Generated by Django 2.2.5 on 2019-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191018_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='bus_unit',
            field=models.CharField(default='No value', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(default='No value', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='estimated_value',
            field=models.BigIntegerField(default='No value'),
        ),
        migrations.AddField(
            model_name='claim',
            name='initiated_by',
            field=models.CharField(default='No value', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='nature',
            field=models.CharField(default='No value', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='original_value',
            field=models.BigIntegerField(default='No value'),
        ),
        migrations.AddField(
            model_name='claim',
            name='po',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='projects',
            field=models.CharField(default='No value', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='resolution',
            field=models.CharField(default='No value', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='responsible_rep',
            field=models.CharField(default='No value', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
