# Generated by Django 2.2.5 on 2019-10-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191018_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claim_type',
        ),
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.TextField(default='No value'),
        ),
    ]
