# Generated by Django 2.2.5 on 2019-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191018_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='contract',
            field=models.BigIntegerField(default='999999'),
        ),
    ]
