# Generated by Django 2.2.5 on 2019-10-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191018_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='description',
        ),
    ]
