# Generated by Django 2.2.5 on 2019-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191018_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='open_date',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(default='No value', max_length=100),
        ),
    ]
