# Generated by Django 2.2.5 on 2019-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191018_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='bus_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='contract',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='estimated_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='initiated_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='nature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='original_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='po',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='projects',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='resolution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='responsible_rep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
