# Generated by Django 2.2.5 on 2019-10-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191018_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claim_type',
        ),
    ]
