# Generated by Django 2.2.5 on 2019-10-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_claim_claim_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='bus_unit',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='original_value',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='po',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='responsible_rep',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='status',
        ),
    ]
