# Generated by Django 2.2.5 on 2019-10-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20191031_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_number',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
