# Generated by Django 2.2.5 on 2019-10-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20191031_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_name',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
