# Generated by Django 2.2.5 on 2019-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20191031_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
