# Generated by Django 2.2.5 on 2019-10-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20191031_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
