# Generated by Django 2.2.5 on 2019-10-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20191031_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
