# Generated by Django 2.2.5 on 2019-10-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_claim_claim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='contract',
            field=models.BigIntegerField(null=True),
        ),
    ]
