# Generated by Django 2.2.5 on 2019-10-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20191031_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.BigIntegerField(null=True)),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('vendor_claim_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Claim')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('comment_claim_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Claim')),
            ],
        ),
    ]
