# Generated by Django 2.2.6 on 2019-11-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_comment_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_claim_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Claim'),
        ),
    ]
