# Generated by Django 2.2.6 on 2019-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20191107_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='contract',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='po',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
