# Generated by Django 2.2.6 on 2019-11-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20191114_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='close_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='resolution',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
