# Generated by Django 2.2.6 on 2019-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20191114_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
