# Generated by Django 2.2.6 on 2019-11-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20191114_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='resolution',
        ),
    ]
