# Generated by Django 2.2.6 on 2019-11-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_claim_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
