# Generated by Django 2.2.6 on 2019-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20191114_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='resolution',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
