# Generated by Django 2.2.6 on 2019-11-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20191114_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='resolution',
            field=models.CharField(default='Blank', max_length=100),
        ),
    ]
