# Generated by Django 2.2.6 on 2019-11-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20191118_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='resolution',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
