# Generated by Django 2.2.6 on 2019-11-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20191130_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_number',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
