# Generated by Django 2.1.15 on 2019-12-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20191130_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='bus_unit',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_type',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='open_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='original_value',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='po',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='responsible_rep',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_claim_ref',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_claim_ref',
        ),
    ]
